"""Assemble the single-file kit: the setup contract plus every script, verbatim.

The user drags ONE file into a Claude conversation. Everything Claude needs is inside it, so
there is no folder to clone, no path to guess, and nothing for a setup to re-derive from a
description -- which is what produced a fresh crop of defects on every cold run.

    python build_kit.py            write the standalone file
    python build_kit.py --check    exit 1 if it is out of date (for the acceptance run)

The generated file is derived output. Edit the contract or the scripts, never the result.
"""

import argparse
import hashlib
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CONTRACT = REPO / "src" / "contract.md"
TOOLS = REPO / "tools"
OUT = REPO / "claude-obsidian-vault-kit.md"

for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, ValueError):
        pass

# Order matters for a human reading top to bottom: shared modules, then tools, then suites.
SHARED = ["vault_paths.py", "_testkit.py", "jobs.json"]
TOOLS_ORDER = ["build_index.py", "check_links.py", "check_duplicates.py",
               "check_freshness.py", "count_tokens.py", "run_suites.py"]
DRIVERS = ["acceptance.py", "verify_setup.py"]

HEADER = """
---

## SECTION 11 — The scripts, verbatim

Everything below is the finished implementation. **Write each block to disk exactly as it stands —
byte for byte, same filename — into the vault's tool folder** (`<VaultRoot>/00_Global/06_tools/`,
created in SECTION 3). Do not retype them from the contracts above, do not "improve" them while
copying, and do not skip the suites: they are the only reason the numbers in SECTION 0 mean
anything.

Measured on Windows 11, Python 3.13, under PowerShell 5.1 **and** Git Bash: 7/7 suites green,
10/10 acceptance checks correct, 10/10 end-to-end setup steps -- ten consecutive runs under each
shell. Copy them and that measurement still applies to what you handed the user. Rewrite them and
it does not.

After writing them, prove it on this machine before you report anything:

```
python <vault>/00_Global/06_tools/run_suites.py       expect 7/7 suites green
python <vault>/00_Global/06_tools/acceptance.py       expect 10/10 checks
python <vault>/00_Global/06_tools/verify_setup.py     expect 10/10 steps
```
"""


def block(name):
    text = (TOOLS / name).read_text(encoding="utf-8")
    lang = "json" if name.endswith(".json") else "python"
    return f"### `{name}`\n\n```{lang}\n{text.rstrip()}\n```\n"


def render():
    contract = CONTRACT.read_text(encoding="utf-8").rstrip()
    parts = [contract, HEADER.rstrip(), ""]
    for group, title in ((SHARED, "Shared"), (TOOLS_ORDER, "Tools"), (DRIVERS, "Drivers")):
        parts.append(f"#### {title}\n")
        for name in group:
            parts.append(block(name))
    for name in sorted(p.name for p in TOOLS.glob("test_*.py")):
        parts.append(block(name))
    parts.append("---\n\n*Generated by `tools/build_kit.py`. Edit the sources, never this file.*\n")
    return "\n".join(parts)


BLOCK_RE = re.compile(r"^### `([^`]+)`\n\n```(?:python|json)\n(.*?)\n```", re.S | re.M)


def verify():
    """Extract the scripts back out of the deliverable and run them.

    Everything else in this repo tests the sources. This tests the artefact the user actually
    receives -- a fence that swallowed a line, a block that never made it in, an embedded copy
    that drifted from tools/. None of those are visible from the source side.
    """
    if not OUT.exists():
        print(f"{OUT.name}: missing -- run build_kit.py", file=sys.stderr)
        return 1
    blocks = BLOCK_RE.findall(OUT.read_text(encoding="utf-8"))
    expected = SHARED + TOOLS_ORDER + DRIVERS + sorted(p.name for p in TOOLS.glob("test_*.py"))
    names = [n for n, _ in blocks]
    if names != expected:
        print(f"{OUT.name}: embedded {len(names)} blocks, expected {len(expected)}\n"
              f"  missing: {sorted(set(expected) - set(names))}\n"
              f"  extra:   {sorted(set(names) - set(expected))}", file=sys.stderr)
        return 1

    work = Path(tempfile.mkdtemp(prefix="vaultkit_roundtrip_")) / "06_tools"
    work.mkdir(parents=True)
    try:
        drifted = []
        for name, body in blocks:
            (work / name).write_text(body + "\n", encoding="utf-8", newline="\n")
            source = (TOOLS / name).read_text(encoding="utf-8").replace("\r\n", "\n").rstrip() + "\n"
            if source != (work / name).read_text(encoding="utf-8"):
                drifted.append(name)
        if drifted:
            print(f"{OUT.name}: embedded copy differs from tools/: {drifted}", file=sys.stderr)
            return 1

        for script, want in (("run_suites.py", "suites green"),
                             ("acceptance.py", "10/10"),
                             ("verify_setup.py", "10/10 steps")):
            result = subprocess.run([sys.executable, str(work / script)],
                                    capture_output=True, cwd=str(work))
            out = result.stdout.decode("utf-8", errors="replace")
            if result.returncode != 0 or want not in out:
                print(f"{script} from the deliverable: exit {result.returncode}\n{out}\n"
                      f"{result.stderr.decode('utf-8', errors='replace')}", file=sys.stderr)
                return 1
            print(f"  ok   {script} runs from the deliverable")
    finally:
        shutil.rmtree(work.parent, ignore_errors=True)
    print(f"{OUT.name}: {len(blocks)} blocks extract, match tools/, and run green")
    return 0


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit 1 when the standalone file does not match the sources")
    parser.add_argument("--verify", action="store_true",
                        help="extract the scripts back out of the deliverable and run them")
    args = parser.parse_args(argv)

    if args.verify:
        return verify()

    rendered = render()
    if args.check:
        if not OUT.exists():
            print(f"{OUT.name}: missing -- run build_kit.py", file=sys.stderr)
            return 1
        current = OUT.read_text(encoding="utf-8")
        if current != rendered:
            print(f"{OUT.name}: out of date -- "
                  f"{hashlib.sha256(current.encode()).hexdigest()[:12]} on disk, "
                  f"{hashlib.sha256(rendered.encode()).hexdigest()[:12]} from sources",
                  file=sys.stderr)
            return 1
        print(f"{OUT.name}: up to date · {len(current.splitlines())} lines")
        return 0

    OUT.write_text(rendered, encoding="utf-8", newline="\n")
    kb = len(rendered.encode("utf-8")) / 1024
    print(f"{OUT.name}: {len(rendered.splitlines())} lines · {kb:.0f} KB · "
          f"{len(SHARED) + len(TOOLS_ORDER) + len(DRIVERS) + len(list(TOOLS.glob('test_*.py')))} files embedded")
    return 0


if __name__ == "__main__":
    sys.exit(main())
