"""Generate the three-level index tree from note frontmatter.

    <VaultRoot>/INDEX - <VaultName>.md                   one line per project     --root
    <Project>/INDEX - <Project>.md                       one line per category    --vault <dir>
    <Project>/<Folder>/INDEX - <Project> <Category>.md   the entries themselves

Reads FRONTMATTER ONLY. There is no code path in this file that opens a note body, which
is the structural guarantee that prose can never leak into the index.

Exit code is 0 only when every entry was clean. Otherwise each defect is printed as
"<filename>: <what is wrong>" on stderr and the exit code is non-zero.
"""

import sys

for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, ValueError):
        pass

import argparse
import re
from collections import defaultdict
from datetime import date
from pathlib import Path
from urllib.parse import quote

from vault_paths import (
    CATEGORY_FOLDERS,
    SKIP_DIRS,
    category_index_name,
    category_label,
    has_forbidden_chars,
    is_index_file,
    log_run,
    project_dirs,
    project_index_name,
    root_index_name,
    walk_markdown,
)

TITLE_MAX = 90
SUMMARY_MAX = 150

HEADER = """# {name} — Index

> Generated by `06_tools/build_index.py` from note frontmatter.
> Do not edit by hand — changes belong in the note itself.
> As of: {today}
"""


class Defects:
    """Collects defects. A non-empty instance makes the run red."""

    def __init__(self):
        self.items = []
        self.skipped = 0

    def add(self, filename, message):
        self.items.append((str(filename), message))

    def report(self):
        for filename, message in self.items:
            print(f"{filename}: {message}", file=sys.stderr)

    def __len__(self):
        return len(self.items)


# --------------------------------------------------------------------------- frontmatter


def read_frontmatter(path, defects):
    """Return the frontmatter mapping of a note, or None if it has none.

    Stops reading at the closing '---'. Body lines are never collected, never returned.
    """
    data = {}
    try:
        with open(path, "r", encoding="utf-8", errors="replace") as fh:
            first = fh.readline()
            if first.strip() != "---":
                return None
            for line in fh:
                if line.strip() in ("---", "..."):
                    return data
                key, sep, value = line.partition(":")
                if not sep:
                    continue
                key = key.strip()
                if not key or key.startswith("#"):
                    continue
                data[key] = _clean_scalar(value)
    except OSError as exc:
        # An error branch that continues is a lost denominator: count it, print it.
        defects.skipped += 1
        defects.add(Path(path).name, f"unreadable ({exc})")
        return None
    # File ended before the closing '---'.
    defects.add(Path(path).name, "frontmatter block is not closed by '---'")
    return data


def _clean_scalar(value):
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return value[1:-1].strip()
    # An unquoted '#' starts a YAML comment. A quoted one (issues: "#12") never reaches here.
    value = re.split(r"\s+#", value, maxsplit=1)[0]
    return value.strip()


MARKDOWN_DEBRIS = re.compile(r"^\s*(?:>+\s*|#{1,6}\s+|[-*+]\s+|\d+\.\s+)")


def clean_summary(raw):
    """Return (cleaned, was_dirty). Debris in summary renders the index line as garbage."""
    text = raw
    dirty = False
    while True:
        stripped = MARKDOWN_DEBRIS.sub("", text)
        if stripped == text:
            break
        text = stripped
        dirty = True
    for marker in ("**", "__", "`"):
        if marker in text:
            text = text.replace(marker, "")
            dirty = True
    if "\n" in text or "\r" in text:
        text = re.sub(r"[\r\n]+", " ", text)
        dirty = True
    collapsed = re.sub(r"\s{2,}", " ", text).strip()
    if collapsed != text.strip():
        dirty = True
    return collapsed, dirty


def truncate(text, limit):
    if len(text) <= limit:
        return text
    return text[: limit - 1].rstrip() + "…"


# --------------------------------------------------------------------------- links


def link_to(vault_root, target_path, label, defects):
    """A [[wikilink]] where Obsidian can resolve one, a markdown link where it cannot.

    The link checker resolves [[...]] and deliberately does not resolve [text](path).
    So every fallback to a markdown link is a defect in the filename, not a workaround.
    """
    rel = Path(target_path).resolve().relative_to(Path(vault_root).resolve()).as_posix()
    name = Path(target_path).name
    if has_forbidden_chars(name):
        defects.add(name, "filename contains one of # [ ] | ^ — cannot be wikilinked")
        return f"[{label}]({quote(rel)})"
    if not name.lower().endswith(".md"):
        # Obsidian does not index these; a [[tool.py]] would be permanently unresolved.
        return f"[{label}]({quote(rel)})"
    return f"[[{rel[:-3]}|{label}]]"


# --------------------------------------------------------------------------- entries


def collect_entries(vault_root, project_dir, folder_name, defects):
    """One entry dict per note in <project>/<folder>. Frontmatter only."""
    folder = Path(project_dir) / folder_name
    entries = []
    if not folder.is_dir():
        return entries
    for path in sorted(folder.glob("*.md")):
        if is_index_file(path):
            continue
        fm = read_frontmatter(path, defects)
        name = path.name
        if fm is None:
            defects.add(name, "no frontmatter block")
            fm = {}

        title = fm.get("title", "").strip()
        if not title:
            defects.add(name, "missing 'title:' — index falls back to the filename")
            title = path.stem

        summary_raw = fm.get("summary", "").strip()
        if not summary_raw:
            defects.add(name, "missing 'summary:'")
        summary, dirty = clean_summary(summary_raw)
        if dirty:
            defects.add(name, "markdown debris in 'summary:' — stripped for the index")
        if summary and summary.strip().lower() == title.strip().lower():
            summary = ""

        prefixes = []
        if fm.get("retired"):
            prefixes.append(f"[retired: {fm['retired']}]")
        if fm.get("stale"):
            prefixes.append(f"[stale since {fm['stale']}]")
        if prefixes:
            summary = " ".join(prefixes) + (f" {summary}" if summary else "")

        entries.append(
            {
                "path": path,
                "title": truncate(title, TITLE_MAX),
                "summary": truncate(summary, SUMMARY_MAX),
                "date": fm.get("updated") or fm.get("created") or "",
                "issues": fm.get("issues", ""),
                "generated": bool(fm.get("generator")),
            }
        )
    return entries


def entry_line(vault_root, entry, defects):
    parts = [f"- {link_to(vault_root, entry['path'], entry['title'], defects)}"]
    tail = []
    if entry["summary"]:
        tail.append(entry["summary"])
    if entry["date"]:
        tail.append(str(entry["date"]))
    if entry["issues"]:
        tail.append(str(entry["issues"]))
    if entry["generated"]:
        tail.append("generated")
    if tail:
        parts.append("— " + " · ".join(tail))
    return " ".join(parts)


# --------------------------------------------------------------------------- writing


def write_if_changed(path, content):
    """Write only on a real change, so a rerun leaves `git status` empty."""
    path = Path(path)
    try:
        if path.exists() and path.read_text(encoding="utf-8") == content:
            return False
    except OSError:
        pass
    path.write_text(content, encoding="utf-8", newline="\n")
    return True


def build_project(vault_root, project_dir, defects):
    """Write every category index plus the project hub. Returns (entries, categories)."""
    project_dir = Path(project_dir).resolve()
    project_name = project_dir.name
    today = date.today().isoformat()
    total_entries = 0
    category_rows = []

    for folder_name in CATEGORY_FOLDERS:
        folder = project_dir / folder_name
        if not folder.is_dir():
            continue
        entries = collect_entries(vault_root, project_dir, folder_name, defects)
        total_entries += len(entries)

        lines = [HEADER.format(name=f"{project_name} — {category_label(folder_name)}", today=today)]
        hub = project_dir / project_index_name(project_dir)
        lines.append(f"↑ {link_to(vault_root, hub, project_name, defects)}\n")
        if entries:
            for entry in entries:
                lines.append(entry_line(vault_root, entry, defects))
        else:
            lines.append("_No notes in this category yet._")
        lines.append("")
        lines.append(f"_{len(entries)} entries._")
        lines.append("")
        write_if_changed(folder / category_index_name(project_name, folder_name), "\n".join(lines))
        category_rows.append((folder_name, len(entries)))

    # A folder nobody configured is a folder nobody indexes. Renaming 06_tools in the file pane
    # once took a real run from 21 categories to 20 with exit 0 and no message -- the notes were
    # simply gone from every index. Say it instead.
    known = set(CATEGORY_FOLDERS)
    for child in sorted(project_dir.iterdir()):
        if not child.is_dir() or child.name.startswith("."):
            continue
        if child.name not in known:
            defects.add(f"{project_name}/{child.name}",
                        "folder is not a configured category - nothing in it reaches an index")

    lines = [HEADER.format(name=project_name, today=today)]
    root_hub = Path(vault_root).resolve() / root_index_name(vault_root)
    lines.append(f"↑ {link_to(vault_root, root_hub, Path(vault_root).resolve().name, defects)}\n")
    for folder_name, count in category_rows:
        target = project_dir / folder_name / category_index_name(project_name, folder_name)
        label = category_label(folder_name)
        lines.append(f"- {link_to(vault_root, target, label, defects)} — {count} entries")
    lines.append("")
    lines.append(f"_{total_entries} entries in {len(category_rows)} categories._")
    lines.append("")
    write_if_changed(project_dir / project_index_name(project_dir), "\n".join(lines))
    return total_entries, len(category_rows)


def build_root(vault_root, defects):
    vault_root = Path(vault_root).resolve()
    today = date.today().isoformat()
    lines = [HEADER.format(name=vault_root.name, today=today)]
    total_entries = 0
    total_categories = 0
    projects = project_dirs(vault_root)
    for project in projects:
        entries, categories = build_project(vault_root, project, defects)
        total_entries += entries
        total_categories += categories
        target = project / project_index_name(project)
        lines.append(
            f"- {link_to(vault_root, target, project.name, defects)} "
            f"— {entries} entries in {categories} categories"
        )
    lines.append("")
    lines.append(f"_{len(projects)} projects · {total_entries} entries in {total_categories} categories._")
    lines.append("")
    write_if_changed(vault_root / root_index_name(vault_root), "\n".join(lines))
    return len(projects), total_entries, total_categories


# --------------------------------------------------------------------------- uniqueness


def check_unique_basenames(vault_root, defects):
    """Doctrine rule 2 needs code reading it, or it holds only while someone remembers it.

    The generator already walks every note, so it counts basenames while it does.
    """
    seen = defaultdict(list)
    for path in walk_markdown(vault_root):
        seen[path.name].append(path)
    for name, paths in sorted(seen.items()):
        if len(paths) > 1:
            where = ", ".join(sorted(p.parent.name for p in paths))
            defects.add(name, f"name used {len(paths)} times ({where})")
    return len(seen)


# --------------------------------------------------------------------------- main


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--root", help="vault root: writes the root index and every project below it")
    group.add_argument("--vault", help="one project directory: writes its category and hub indexes")
    args = parser.parse_args(argv)

    defects = Defects()

    if args.root:
        vault_root = Path(args.root).resolve()
        if not vault_root.is_dir():
            print(f"not a directory: {vault_root}", file=sys.stderr)
            return 2
        projects, entries, categories = build_root(vault_root, defects)
        names = check_unique_basenames(vault_root, defects)
        print(f"{entries} entries in {categories} categories · {projects} projects · {names} distinct filenames")
    else:
        project_dir = Path(args.vault).resolve()
        if not project_dir.is_dir():
            print(f"not a directory: {project_dir}", file=sys.stderr)
            return 2
        vault_root = project_dir.parent
        entries, categories = build_project(vault_root, project_dir, defects)
        names = check_unique_basenames(vault_root, defects)
        print(f"{entries} entries in {categories} categories · {project_dir.name} · {names} distinct filenames")

    if defects.skipped:
        print(f"skipped {defects.skipped} unreadable files", file=sys.stderr)

    status = "ok" if not defects else "defects"
    log_run(vault_root, "build_index", status, f"{len(defects)} defects")

    if defects:
        defects.report()
        print(f"{len(defects)} defects", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
