"""Generate the three-level index tree from note frontmatter.

    <VaultRoot>/INDEX - <VaultName>.md                   one line per project     --root
    <Project>/INDEX - <Project>.md                       one line per category    --vault <dir>
    <Project>/<Folder>/INDEX - <Project> <Category>.md   the entries themselves

Reads FRONTMATTER ONLY. There is no code path in this file that opens a note body, which
is the structural guarantee that prose can never leak into the index.

It also owns the shape of a project: a project folder that is missing category folders gets
them, and a folder the user made by hand becomes a category of its own. Both are printed --
they change the tree, and a run that changes the tree silently is the failure this whole
file exists to prevent. Neither is a defect.

Exit code is 0 only when every entry was clean. Otherwise each defect is printed as
"<filename>: <what is wrong>" on stderr and the exit code is non-zero.
"""

import sys

for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, ValueError):
        pass

import argparse
import re
from collections import defaultdict
from datetime import date
from pathlib import Path
from urllib.parse import quote

from vault_paths import (
    CATEGORY_FOLDERS,
    SKIP_DIRS,
    TEMPLATES_DIR,
    category_index_name,
    category_label,
    has_forbidden_chars,
    is_index_file,
    log_run,
    project_dirs,
    project_index_name,
    root_index_name,
    template_name,
    template_text,
    walk_markdown,
)

TITLE_MAX = 90
SUMMARY_MAX = 150

HEADER = """# {name} — Index

> Generated by `06_tools/vaultkit.py index` from note frontmatter.
> Do not edit by hand — changes belong in the note itself.
> As of: {today}
"""


class Defects:
    """Collects defects. A non-empty instance makes the run red."""

    def __init__(self):
        self.items = []
        self.skipped = 0

    def add(self, filename, message):
        self.items.append((str(filename), message))

    def report(self):
        for filename, message in self.items:
            print(f"{filename}: {message}", file=sys.stderr)

    def __len__(self):
        return len(self.items)


# --------------------------------------------------------------------------- frontmatter


def read_frontmatter(path, defects):
    """Return the frontmatter mapping of a note, or None if it has none.

    Stops reading at the closing '---'. Body lines are never collected, never returned.
    """
    data = {}
    try:
        # utf-8-sig, not utf-8: a byte-order mark survives str.strip() -- "﻿".isspace()
        # is False -- so the opening '---' of a note written by a Windows editor fails this
        # test. The note then reads as having no frontmatter at all: its title and summary
        # are gone from the index and the run goes red over a file the user wrote correctly.
        # utf-8-sig drops a BOM if there is one and behaves like utf-8 if there is not.
        with open(path, "r", encoding="utf-8-sig", errors="replace") as fh:
            first = fh.readline()
            if first.strip() != "---":
                return None
            for line in fh:
                if line.strip() in ("---", "..."):
                    return data
                key, sep, value = line.partition(":")
                if not sep:
                    continue
                key = key.strip()
                if not key or key.startswith("#"):
                    continue
                data[key] = _clean_scalar(value)
    except OSError as exc:
        # An error branch that continues is a lost denominator: count it, print it.
        defects.skipped += 1
        defects.add(Path(path).name, f"unreadable ({exc})")
        return None
    # File ended before the closing '---'.
    defects.add(Path(path).name, "frontmatter block is not closed by '---'")
    return data


def _clean_scalar(value):
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
        return value[1:-1].strip()
    # An unquoted '#' starts a YAML comment. A quoted one (issues: "#12") never reaches here.
    value = re.split(r"\s+#", value, maxsplit=1)[0]
    return value.strip()


MARKDOWN_DEBRIS = re.compile(r"^\s*(?:>+\s*|#{1,6}\s+|[-*+]\s+|\d+\.\s+)")


def clean_summary(raw):
    """Return (cleaned, was_dirty). Debris in summary renders the index line as garbage."""
    text = raw
    dirty = False
    while True:
        stripped = MARKDOWN_DEBRIS.sub("", text)
        if stripped == text:
            break
        text = stripped
        dirty = True
    for marker in ("**", "__", "`"):
        if marker in text:
            text = text.replace(marker, "")
            dirty = True
    if "\n" in text or "\r" in text:
        text = re.sub(r"[\r\n]+", " ", text)
        dirty = True
    collapsed = re.sub(r"\s{2,}", " ", text).strip()
    if collapsed != text.strip():
        dirty = True
    return collapsed, dirty


def truncate(text, limit):
    if len(text) <= limit:
        return text
    return text[: limit - 1].rstrip() + "…"


# --------------------------------------------------------------------------- links


def link_to(vault_root, target_path, label, defects):
    """A [[wikilink]] where Obsidian can resolve one, a markdown link where it cannot.

    The link checker resolves [[...]] and deliberately does not resolve [text](path).
    So every fallback to a markdown link is a defect in the filename, not a workaround.
    """
    name = Path(target_path).name
    try:
        rel = Path(target_path).resolve().relative_to(Path(vault_root).resolve()).as_posix()
    except ValueError:
        # A junction or symlink inside the vault whose target resolves outside the root.
        # relative_to() raises there, and this used to leave the function as a traceback -- so
        # the run died before log_run() at the end of main(), which is the one outcome this kit
        # forbids: silence has to mean "did not run". There is no link to write either way (a
        # [[wikilink]] needs a vault-relative path and there is none), so the label goes in as
        # plain text and the defect line carries the reason.
        defects.add(name, "resolves outside the vault root — not linkable "
                          "(a junction or symlink pointing out of the vault?)")
        return label
    if has_forbidden_chars(name):
        defects.add(name, "filename contains one of # [ ] | ^ — cannot be wikilinked")
        return f"[{label}]({quote(rel)})"
    if not name.lower().endswith(".md"):
        # Obsidian does not index these; a [[tool.py]] would be permanently unresolved.
        return f"[{label}]({quote(rel)})"
    return f"[[{rel[:-3]}|{label}]]"


# --------------------------------------------------------------------------- entries


def collect_entries(vault_root, project_dir, folder_name, defects):
    """One entry dict per note in <project>/<folder>. Frontmatter only."""
    folder = Path(project_dir) / folder_name
    entries = []
    if not folder.is_dir():
        return entries
    # Resolved once, not per note: Path('.').name is the empty string, and every note in the
    # folder would then be reported as disagreeing with a project called "".
    project_name = Path(project_dir).resolve().name
    for path in sorted(folder.glob("*.md")):
        if is_index_file(path):
            continue
        fm = read_frontmatter(path, defects)
        name = path.name
        if fm is None:
            defects.add(name, "no frontmatter block")
            fm = {}

        title = fm.get("title", "").strip()
        if not title:
            defects.add(name, "missing 'title:' — index falls back to the filename")
            title = path.stem

        summary_raw = fm.get("summary", "").strip()
        if not summary_raw:
            defects.add(name, "missing 'summary:'")
        summary, dirty = clean_summary(summary_raw)
        if dirty:
            defects.add(name, "markdown debris in 'summary:' — stripped for the index")
        if summary and summary.strip().lower() == title.strip().lower():
            summary = ""

        # 'project:' is advisory -- the folder decides where a note is indexed, and nothing here
        # reads this field to place anything. Absent, it means nothing and stays silent. Present
        # and disagreeing, it is two sources claiming different things while only one of them
        # acts, which is the defect: the note is indexed under the folder and the frontmatter
        # says otherwise, forever, with no message. Compared exactly, case included -- the folder
        # name IS the project name and goes into every wikilink as it stands.
        declared = fm.get("project", "").strip()
        if declared and declared != project_name:
            defects.add(name, f"'project: {declared}' disagrees with the folder "
                              f"({project_name}) — the folder decides where a note is indexed")

        prefixes = []
        if fm.get("retired"):
            prefixes.append(f"[retired: {fm['retired']}]")
        if fm.get("stale"):
            prefixes.append(f"[stale since {fm['stale']}]")
        if prefixes:
            summary = " ".join(prefixes) + (f" {summary}" if summary else "")

        entries.append(
            {
                "path": path,
                "title": truncate(title, TITLE_MAX),
                "summary": truncate(summary, SUMMARY_MAX),
                "date": fm.get("updated") or fm.get("created") or "",
                "issues": fm.get("issues", ""),
                "generated": bool(fm.get("generator")),
            }
        )
    return entries


def entry_line(vault_root, entry, defects):
    parts = [f"- {link_to(vault_root, entry['path'], entry['title'], defects)}"]
    tail = []
    if entry["summary"]:
        tail.append(entry["summary"])
    if entry["date"]:
        tail.append(str(entry["date"]))
    if entry["issues"]:
        tail.append(str(entry["issues"]))
    if entry["generated"]:
        tail.append("generated")
    if tail:
        parts.append("— " + " · ".join(tail))
    return " ".join(parts)


# --------------------------------------------------------------------------- writing


def write_if_changed(path, content, defects):
    """Write only on a real change, so a rerun leaves `git status` empty.

    THE WRITE IS INSIDE A try, AND THAT IS THE WHOLE POINT (2026-07-31). It used to sit outside
    one, so a read-only or locked INDEX file -- a vault on OneDrive is not a theoretical case --
    raised PermissionError out of here and took the run down BEFORE log_run() at the end of
    main(). The result was half an index tree AND not one line in runs.log: not `defects`, not
    `did-not-run`, nothing at all. Silence is the one thing that has to keep meaning "did not
    run", and a crash on the way to the log turns it into a lie.

    Two try blocks, not one, and the split is deliberate: a file that cannot be READ may still be
    writable, and overwriting it is the repair. Merging them would turn that case into a defect
    and skip the write that would have fixed it.

    Measured on this machine 2026-07-31, on a copy of a real vault (491 .md), with `attrib +R` on
    `Horus-F5Tts-Onnx/00_Notes/INDEX - Horus-F5Tts-Onnx Notes.md` -- the third project of seven,
    so most of the tree comes before it:

      before   PermissionError traceback · 46 of 61 index files written · runs.log absent
      after    exit 1 · the filename on stderr · 61 of 61 written · `build_index defects` logged
      unlock   `attrib -R`, rerun: exit 0, tree complete
      again    third run writes nothing, `git status` stays empty

    The reset path is the point of quoting the numbers: `attrib -R` on the same file puts the
    copy back, so anyone can rerun this without guessing what state it left behind.
    """
    path = Path(path)
    try:
        if path.exists() and path.read_text(encoding="utf-8") == content:
            return False
    except OSError:
        # Unreadable, possibly writable. Fall through to the write, which is the repair.
        pass
    try:
        path.write_text(content, encoding="utf-8", newline="\n")
    except OSError as exc:
        defects.add(path.name, f"not written ({exc})")
        return False
    return True


def scaffold(project_dir, defects):
    """Create the category folders this project is missing. Returns the names created.

    A project folder a user makes in the file pane is empty. Leaving it that way means the
    user has to know the six names and type them correctly before anything they write is
    indexed -- so the run creates them instead, and says which ones it made.
    """
    created = []
    for folder_name in CATEGORY_FOLDERS:
        folder = project_dir / folder_name
        if folder.is_dir():
            continue
        try:
            folder.mkdir(parents=True, exist_ok=True)
        except OSError as exc:
            defects.add(f"{project_dir.name}/{folder_name}", f"category folder not created ({exc})")
            continue
        created.append(folder_name)
    return created


def project_categories(project_dir):
    """Every category of this project: the configured ones first, then the hand-made ones.

    CATEGORY_FOLDERS is what a project is *created* with, not the only thing it may hold.
    A folder the user adds themselves is a category they meant to have, so it is adopted and
    indexed like any other. Returns (folder_names, adopted_names).

    The alternative -- calling an unknown folder a defect -- was the behaviour up to here, and
    it made the run red for a user doing something the structure explicitly allows. What must
    not happen is the *silent* version: a renamed 06_tools once took a real run from 21
    categories to 20 with exit 0 and no message, and every note in it was simply gone from
    every index. Adoption keeps those notes indexed; main() prints the folder either way.
    """
    known = set(CATEGORY_FOLDERS)
    adopted = []
    for child in sorted(project_dir.iterdir()):
        if not child.is_dir() or child.name.startswith(".") or child.name in SKIP_DIRS:
            continue
        if child.name not in known:
            adopted.append(child.name)
    return CATEGORY_FOLDERS + adopted, adopted


def build_project(vault_root, project_dir, defects):
    """Write every category index plus the project hub.

    Returns (entries, categories, created, adopted) -- the last two are folder names, and main()
    prints them. A run that creates a folder and does not say so is a run that changed the tree
    behind the user's back.
    """
    project_dir = Path(project_dir).resolve()
    project_name = project_dir.name
    today = date.today().isoformat()
    total_entries = 0
    category_rows = []

    created = scaffold(project_dir, defects)
    folder_names, adopted = project_categories(project_dir)

    for folder_name in folder_names:
        folder = project_dir / folder_name
        if not folder.is_dir():
            continue
        entries = collect_entries(vault_root, project_dir, folder_name, defects)
        total_entries += len(entries)

        lines = [HEADER.format(name=f"{project_name} — {category_label(folder_name)}", today=today)]
        hub = project_dir / project_index_name(project_dir)
        lines.append(f"↑ {link_to(vault_root, hub, project_name, defects)}\n")
        if entries:
            for entry in entries:
                lines.append(entry_line(vault_root, entry, defects))
        else:
            lines.append("_No notes in this category yet._")
        lines.append("")
        lines.append(f"_{len(entries)} entries._")
        lines.append("")
        write_if_changed(folder / category_index_name(project_name, folder_name),
                         "\n".join(lines), defects)
        category_rows.append((folder_name, len(entries)))

    lines = [HEADER.format(name=project_name, today=today)]
    root_hub = Path(vault_root).resolve() / root_index_name(vault_root)
    lines.append(f"↑ {link_to(vault_root, root_hub, Path(vault_root).resolve().name, defects)}\n")
    for folder_name, count in category_rows:
        target = project_dir / folder_name / category_index_name(project_name, folder_name)
        label = category_label(folder_name)
        lines.append(f"- {link_to(vault_root, target, label, defects)} — {count} entries")
    lines.append("")
    lines.append(f"_{total_entries} entries in {len(category_rows)} categories._")
    lines.append("")
    write_if_changed(project_dir / project_index_name(project_dir), "\n".join(lines), defects)
    return total_entries, len(category_rows), created, adopted


def write_templates(vault_root, projects, defects):
    """One note template per project under <VaultRoot>/_templates/. Returns what it created.

    CREATED WHEN MISSING, NEVER OVERWRITTEN. A template exists to be edited -- a user adds the
    fields their vault actually uses -- and a tool that rewrites it on every run eats that edit
    without saying so. The doctrine rule that generated files are not hand-edited covers the
    index tree; _templates is deliberately not part of it, which is why it is written once and
    then left alone.

    THE SAME FAILURE MODE write_if_changed() HAD, AND THE SAME REPAIR. This runs at the very end
    of build_root(), so a read-only `_templates` folder raised OSError here and took the run down
    on the last step before log_run() -- a complete index tree, and still not one line in
    runs.log saying the run happened. A missing template is a defect, not a reason to lose the
    record of everything that did work.
    """
    folder = Path(vault_root).resolve() / TEMPLATES_DIR
    written = []
    for project in projects:
        target = folder / template_name(project.name)
        if target.exists():
            continue
        try:
            folder.mkdir(parents=True, exist_ok=True)
            target.write_text(template_text(project.name), encoding="utf-8", newline="\n")
        except OSError as exc:
            defects.add(target.name, f"note template not written ({exc})")
            continue
        written.append(target.name)
    return written


def build_root(vault_root, defects):
    vault_root = Path(vault_root).resolve()
    today = date.today().isoformat()
    lines = [HEADER.format(name=vault_root.name, today=today)]
    total_entries = 0
    total_categories = 0
    created_all = []
    adopted_all = []
    projects = project_dirs(vault_root)
    for project in projects:
        entries, categories, created, adopted = build_project(vault_root, project, defects)
        total_entries += entries
        total_categories += categories
        created_all += [f"{project.name}/{n}" for n in created]
        adopted_all += [f"{project.name}/{n}" for n in adopted]
        target = project / project_index_name(project)
        lines.append(
            f"- {link_to(vault_root, target, project.name, defects)} "
            f"— {entries} entries in {categories} categories"
        )
    lines.append("")
    lines.append(f"_{len(projects)} projects · {total_entries} entries in {total_categories} categories._")
    lines.append("")
    write_if_changed(vault_root / root_index_name(vault_root), "\n".join(lines), defects)
    templates = write_templates(vault_root, projects, defects)
    return len(projects), total_entries, total_categories, created_all, adopted_all, templates


# --------------------------------------------------------------------------- uniqueness


def check_unique_basenames(vault_root, defects):
    """Doctrine rule 2 needs code reading it, or it holds only while someone remembers it.

    The generator already walks every note, so it counts basenames while it does.
    """
    seen = defaultdict(list)
    for path in walk_markdown(vault_root):
        seen[path.name].append(path)
    for name, paths in sorted(seen.items()):
        if len(paths) > 1:
            where = ", ".join(sorted(p.parent.name for p in paths))
            defects.add(name, f"name used {len(paths)} times ({where})")
    return len(seen)


# --------------------------------------------------------------------------- main


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--root", help="vault root: writes the root index and every project below it")
    group.add_argument("--vault", help="one project directory: writes its category and hub indexes")
    args = parser.parse_args(argv)

    defects = Defects()

    if args.root:
        vault_root = Path(args.root).resolve()
        if not vault_root.is_dir():
            print(f"not a directory: {vault_root}", file=sys.stderr)
            return 2
        projects, entries, categories, created, adopted, templates = build_root(vault_root, defects)
        names = check_unique_basenames(vault_root, defects)
        print(f"{entries} entries in {categories} categories · {projects} projects · {names} distinct filenames")
    else:
        project_dir = Path(args.vault).resolve()
        if not project_dir.is_dir():
            print(f"not a directory: {project_dir}", file=sys.stderr)
            return 2
        vault_root = project_dir.parent
        entries, categories, created_names, adopted_names = build_project(vault_root, project_dir, defects)
        created = [f"{project_dir.name}/{n}" for n in created_names]
        adopted = [f"{project_dir.name}/{n}" for n in adopted_names]
        # Templates are written by the root run only: it is the one invocation that knows every
        # project, and _templates sits at the vault root, not inside a project.
        templates = []
        names = check_unique_basenames(vault_root, defects)
        print(f"{entries} entries in {categories} categories · {project_dir.name} · {names} distinct filenames")

    # Neither of these is a defect -- the run does exactly what the structure allows. Both change
    # or extend the tree, so both are said out loud. A typo'd folder name shows up here as a
    # category the user did not mean to have, which is the only warning that case ever gets.
    for name in created:
        print(f"  created  {name} — category folder was missing")
    for name in adopted:
        print(f"  adopted  {name} — folder made by hand, indexed as a category")
    for name in templates:
        print(f"  template {TEMPLATES_DIR}/{name} — note template written once; edit it freely, "
              f"no run overwrites it")

    if defects.skipped:
        print(f"skipped {defects.skipped} unreadable files", file=sys.stderr)

    status = "ok" if not defects else "defects"
    log_run(vault_root, "build_index", status,
            f"{len(defects)} defects · {len(created)} created · {len(adopted)} adopted · "
            f"{len(templates)} templates")

    if defects:
        defects.report()
        print(f"{len(defects)} defects", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
