"""Assemble the single-file kit: the setup contract plus every script, verbatim.

The user drags ONE file into a Claude conversation. Everything Claude needs is inside it, so
there is no folder to clone, no path to guess, and nothing for a setup to re-derive from a
description -- which is what produced a fresh crop of defects on every cold run.

    python build_kit.py            write the standalone file
    python build_kit.py --check    exit 1 if it is out of date (for the acceptance run)

The generated file is derived output. Edit the contract or the scripts, never the result.
"""

import argparse
import hashlib
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
CONTRACT = REPO / "src" / "contract.md"
TOOLS = REPO / "tools"
OUT = REPO / "claude-obsidian-vault-kit.md"

for _stream in (sys.stdout, sys.stderr):
    try:
        _stream.reconfigure(encoding="utf-8", errors="replace")
    except (AttributeError, ValueError):
        pass

# Order matters for a human reading top to bottom: shared modules, then tools, then suites.
SHARED = ["vault_paths.py", "_testkit.py", "jobs.json"]
TOOLS_ORDER = ["build_index.py", "check_links.py", "check_duplicates.py",
               "check_freshness.py", "count_tokens.py", "run_suites.py"]
DRIVERS = ["acceptance.py", "verify_setup.py", "upgrade.py"]

HEADER = """
---

## SECTION 10 — The scripts, verbatim

Everything below is the finished implementation. **Write each block to disk exactly as it stands —
byte for byte, same filename — into the vault's tool folder** (`<VaultRoot>/00_Global/06_tools/`,
created in SECTION 3). Do not retype them from the contracts above, do not "improve" them while
copying, and do not skip the suites: they are the only reason the numbers in SECTION 0 mean
anything.

Measured on Windows 11, Python 3.13, under PowerShell 5.1 **and** Git Bash: 8/8 suites green,
10/10 acceptance checks correct, 11/11 end-to-end setup steps -- ten consecutive runs under each
shell. Copy them and that measurement still applies to what you handed the user. Rewrite them and
it does not.

**Write them as UTF-8 without a byte-order mark.** `Set-Content -Encoding utf8` under PowerShell 5.1
prepends a BOM, and a BOM in front of `import sys` is an invisible first character that some readers
choke on. Use your file-writing tool, or Python. This cost a full round on one setup, and the error
pointed at the wrong line.

After writing them, prove it on this machine before you report anything:

```
python <vault>/00_Global/06_tools/run_suites.py       expect 8/8 suites green
python <vault>/00_Global/06_tools/acceptance.py       expect 10/10 checks
python <vault>/00_Global/06_tools/verify_setup.py     expect 11/11 steps
```
"""


def block(name):
    text = (TOOLS / name).read_text(encoding="utf-8")
    lang = "json" if name.endswith(".json") else "python"
    return f"### `{name}`\n\n```{lang}\n{text.rstrip()}\n```\n"


def source_version(body):
    """Twelve hex digits over the delivered file itself, minus the stamp line.

    A date would answer "how old is this" and nothing else; two people with different files
    could still read the same date. Hashing the *sources* instead looked equivalent and was
    not: the SECTION 10 header lives in this script, so editing it changed what users receive
    while the version stayed put -- two different files claiming to be the same one. Hash what
    is shipped.
    """
    return hashlib.sha256(body.encode("utf-8")).hexdigest()[:12]


def render():
    contract = CONTRACT.read_text(encoding="utf-8").rstrip()
    parts = ["", contract, HEADER.rstrip(), ""]
    for group, title in ((SHARED, "Shared"), (TOOLS_ORDER, "Tools"), (DRIVERS, "Drivers")):
        parts.append(f"#### {title}\n")
        for name in group:
            parts.append(block(name))
    for name in sorted(p.name for p in TOOLS.glob("test_*.py")):
        parts.append(block(name))
    parts.append("---\n\n*Generated by `tools/build_kit.py`. Edit the sources, never this file.*\n"
                 "*Compare the `kit-version` at the top against the published file to see whether "
                 "this copy is current.*\n")
    body = "\n".join(parts)
    return f"<!-- kit-version: {source_version(body)} -->{body}"


BLOCK_RE = re.compile(r"^### `([^`]+)`\n\n```(?:python|json)\n(.*?)\n```", re.S | re.M)


def verify():
    """Extract the scripts back out of the deliverable and run them.

    Everything else in this repo tests the sources. This tests the artefact the user actually
    receives -- a fence that swallowed a line, a block that never made it in, an embedded copy
    that drifted from tools/. None of those are visible from the source side.
    """
    if not OUT.exists():
        print(f"{OUT.name}: missing -- run build_kit.py", file=sys.stderr)
        return 1
    blocks = BLOCK_RE.findall(OUT.read_text(encoding="utf-8"))
    expected = SHARED + TOOLS_ORDER + DRIVERS + sorted(p.name for p in TOOLS.glob("test_*.py"))
    names = [n for n, _ in blocks]
    if names != expected:
        print(f"{OUT.name}: embedded {len(names)} blocks, expected {len(expected)}\n"
              f"  missing: {sorted(set(expected) - set(names))}\n"
              f"  extra:   {sorted(set(names) - set(expected))}", file=sys.stderr)
        return 1

    work = Path(tempfile.mkdtemp(prefix="vaultkit_roundtrip_")) / "06_tools"
    work.mkdir(parents=True)
    try:
        drifted = []
        for name, body in blocks:
            (work / name).write_text(body + "\n", encoding="utf-8", newline="\n")
            source = (TOOLS / name).read_text(encoding="utf-8").replace("\r\n", "\n").rstrip() + "\n"
            if source != (work / name).read_text(encoding="utf-8"):
                drifted.append(name)
        if drifted:
            print(f"{OUT.name}: embedded copy differs from tools/: {drifted}", file=sys.stderr)
            return 1

        # Substrings without counts on purpose. Exit 0 already means every check passed, and a
        # literal "10/10" here is a number in a second place that goes stale the moment a
        # fixture or a step is added -- which is the defect this file checks the prose for.
        for script, want in (("run_suites.py", "suites green"),
                             ("acceptance.py", "checks behaved as specified"),
                             ("verify_setup.py", "steps every time")):
            result = subprocess.run([sys.executable, str(work / script)],
                                    capture_output=True, cwd=str(work))
            out = result.stdout.decode("utf-8", errors="replace")
            if result.returncode != 0 or want not in out:
                print(f"{script} from the deliverable: exit {result.returncode}\n{out}\n"
                      f"{result.stderr.decode('utf-8', errors='replace')}", file=sys.stderr)
                return 1
            print(f"  ok   {script} runs from the deliverable")
    finally:
        shutil.rmtree(work.parent, ignore_errors=True)
    # Prose only. The embedded suites contain strings like "0/2 suites" as test data, and
    # counting those as claims makes the guard cry wolf on its own fixtures.
    suites = len(list(TOOLS.glob("test_*.py")))
    prose = CONTRACT.read_text(encoding="utf-8") + HEADER
    claimed = set(re.findall(r"(\d+)/\d+ suites", prose))
    wrong = sorted(n for n in claimed if int(n) != suites)
    if wrong:
        print(f"{OUT.name}: text claims {'/'.join(wrong)} suites, {suites} exist. "
              f"A number in prose goes stale the moment a suite is added -- this check exists "
              f"because one shipped that way.", file=sys.stderr)
        return 1

    # Same class of defect, one level nastier: a real hash quoted in the prose as an example.
    # The file then carries two kit-version lines, only one of them true, and a reader comparing
    # copies has no way to tell which. Write the example as an ellipsis.
    stale_stamps = re.findall(r"kit-version: ([0-9a-f]{12})", prose)
    if stale_stamps:
        print(f"{OUT.name}: prose quotes a literal kit-version {stale_stamps}. The stamp on line 1 "
              f"is the only true one -- a second one goes stale on the next build and reads as if "
              f"the copy were outdated. Use `<!-- kit-version: … -->`.", file=sys.stderr)
        return 1

    print(f"{OUT.name}: {len(blocks)} blocks extract, match tools/, and run green · "
          f"every suite count in the text says {suites} · no stale stamp quoted in the prose")
    return 0


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit 1 when the standalone file does not match the sources")
    parser.add_argument("--verify", action="store_true",
                        help="extract the scripts back out of the deliverable and run them")
    args = parser.parse_args(argv)

    if args.verify:
        return verify()

    rendered = render()
    if args.check:
        if not OUT.exists():
            print(f"{OUT.name}: missing -- run build_kit.py", file=sys.stderr)
            return 1
        current = OUT.read_text(encoding="utf-8")
        if current != rendered:
            print(f"{OUT.name}: out of date -- "
                  f"{hashlib.sha256(current.encode()).hexdigest()[:12]} on disk, "
                  f"{hashlib.sha256(rendered.encode()).hexdigest()[:12]} from sources",
                  file=sys.stderr)
            return 1
        print(f"{OUT.name}: up to date · {len(current.splitlines())} lines")
        return 0

    OUT.write_text(rendered, encoding="utf-8", newline="\n")
    kb = len(rendered.encode("utf-8")) / 1024
    print(f"{OUT.name}: {len(rendered.splitlines())} lines · {kb:.0f} KB · "
          f"{len(SHARED) + len(TOOLS_ORDER) + len(DRIVERS) + len(list(TOOLS.glob('test_*.py')))} files embedded")
    return 0


if __name__ == "__main__":
    sys.exit(main())
